language: node_js
node_js:
  - 7
sudo: required

services:
- docker

before_install:
- cd ${TRAVIS_BUILD_DIR}/ts
- ./docker-nodeprof/docker-build.sh
- npm install
- npm run build
- jest -t basic-assignment-tainted
