name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://mwaldrich/docker-nodeprof
    - uses: actions/javascript-action@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
    - run: rm -rf node_modules/
    - run: npm ci
    - run: npm run build
    - run: ./node_modules/.bin/jest

