name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted
    container: mwaldrich/docker-nodeprof
    env:
      working-directory: ./ts

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - uses: actions/javascript-action@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
    - run: npm install
      working-directory: ./ts
    - run: npm run build
      working-directory: ./ts
    - run: /usr/bin/sudo ./node_modules/.bin/jest
      working-directory: ./ts

