name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/javascript-action@v1
    - run: cd /home/runner/work/augur/augur/ts
    - uses: docker://mwaldrich/docker-nodeprof
    - run: npm install
    - run: npm run build
    - run: ./node_modules/.bin/jest

